openapi: 3.0.0
info:
  title: Order automation API
  description: This is an API which was creaed as a project at TechMagic academy.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Server which hosts this API

paths:
  /products:
    get:
      tags:
        - main
      summary: Returns a list of products
      responses:
        "200":
          description: A JSON array of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        "default":
          description: Error fetching products happened
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - admin
      summary: Add a new product
      description: Add a new pet to the store
      requestBody:
        description: Create a new product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: Invalid input
        "422":
          description: Validation exception


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          example: kljw3l2fsdof993j3
        title:
          type: string
          example: Guitar
        price:
          type: number
          example: 1000
        delivery:
          type: array
          example: ['Standard', 'Express']
        description:
          type: string
          example: A great guitar
        image:
          type: string
          example: https://sc1.musik-produktiv.com/pic-010153533xl/suhr-custom-modern-3ts.jpg
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    Error:
      type: object
      properties:
        message:
          type: string
          example: Some Error
        statusCode:
          type: number
          example: 404